# Generated by Django 5.1.6 on 2025-02-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="habit_tracker",
            new_name="habit",
        ),
    ]
